---
- name: Launch Instance
  ec2:
    key_name: bootstrap
    instance_type: t2.nano
    image: ami-fce3c696
    wait: yes
    count: 1
    group_id: sg-725c1016
    vpc_subnet_id: subnet-8c5dc8d5
    assign_public_ip: yes
  register: ec2
    
- name: Add the new EC2 host(s)
  add_host: name={{item.public_ip}}
  with_items: "{{ec2.instances}}"

- name: Wait for SSH
  local_action: wait_for host={{item.public_ip}} port=22 delay=15 state=started
  with_items: "{{ec2.instances}}"
  
- name: Load and populate Conjur policy
  local_action: script /mnt/ansible-ec2/load_policy.sh {{item.public_ip}}
  with_items: "{{ec2.instances}}"